### ISSUE TITLE
Github repo access request

### ISSUE THREAD

**Issue by kendallyoung** [newjersey/innovation.nj.gov#172]
Nissi Thomas (NJ OIM employee) needs access to commit changes to the [dol-ui-claimant-intake-infra](https://github.com/newjersey/dol-ui-claimant-intake-infra/tree/main) repo. 
Nissi is embedded on the Nava Data & Integrations scrum team. Her github username is [Nissi-1](https://github.com/Nissi-1).

**Comment by billyhunt** [comment]
@seidior Is there anything I can do to move this ticket along?

**Comment by seidior** [comment]
@billyhunt Yes, do you mind re-posting this issue in the appropriate repository please? We don't track operations requests in this repo.

**Comment by billyhunt** [comment]
I will!  Thanks!

**Comment by billyhunt** [comment]
Done!  The ticket is here. https://github.com/newjersey/internal-ops/issues/371

Thank you so much!
